FROM python:3-slim
EXPOSE 8080
WORKDIR /app
RUN apt-get update \
    && apt-get install --no-install-recommends -y build-essential \
    && pip install uwsgi \
    && apt-get remove --purge -y build-essential \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ADD requirements.txt ./
RUN pip install -r requirements.txt
ADD ./ ./
CMD [ "uwsgi", "--socket", "0.0.0.0:8080", "--protocol", "http", "-w", "main:app" ]