FROM python:3
EXPOSE 8080
WORKDIR /app
RUN pip install uwsgi
ADD requirements.txt ./
RUN pip install -r requirements.txt
ADD ./ ./
CMD [ "uwsgi", "--socket", "0.0.0.0:8080", "--protocol", "http", "-w", "main:app" ]